WIP: Connect all node devices
2gis/stf-utils pull request #35
Opened 2017-07-27 08:32 UTC by z00sts

2017-07-28 03:54 UTC, skyline-gleb commented on stf_utils/common/stfapi.py
> +                    log.warning("Forbidden! %s" % response.json())
это не похоже на тебя :)

2017-07-28 03:55 UTC, z00sts commented on stf_utils/common/stfapi.py
> +                    log.warning("Forbidden! %s" % response.json())
warn - deprecated, мне pycharm и Коля говорили

2017-07-28 04:12 UTC, skyline-gleb commented on stf_utils/stf_connect/client.py
> +                    log.warning("ADB connection with device %s was lost. "
да и тут тоже можно сразу на `format` махнуть

2017-07-28 04:15 UTC, skyline-gleb commented on stf_utils/common/stfapi.py
> +                    log.warning("Forbidden! %s" % response.json())
не угадал) яж про `%` vs `format`

2017-07-28 08:08 UTC, z00sts commented
@skyline-gleb переделал слегка

2017-07-28 09:19 UTC, skyline-gleb requested changes

2017-07-28 09:19 UTC, skyline-gleb commented on stf_utils/stf_connect/client.py
> +        self.stf = stf_client
очень сильно сомневаюсь в идеи наделить тупой `Device` знанием, что такое `stf_client` и ходить в него каждый раз, когда узнаем у девайса эти параметры. Поэтому пусть бы клиент этим и занимался, его это забота

2017-07-28 09:19 UTC, skyline-gleb commented on stf_utils/stf_connect/client.py
> +                    "wanted_amount": self.get_wanted_amount(wanted_device_group),
не правильно тут считать это. Переиспользование `get_wanted_amount` сейчас у тебя в `connect_devices` всегда возвращает все подходящие девайсы невзирая на заданное пользоваталем в конфиге, так как тут делаешь `get_wanted_amount(wanted_device_group FROM self.device_spec)`. А в `connect_devices` это `get_wanted_amount(device_group FROM self.device_groups)`

2017-07-28 09:19 UTC, skyline-gleb commented on stf_utils/stf_connect/client.py
> +        _amount = group.get("amount", None)
в связи с комментарием ниже, приходим к выводу что здесь не `amount`, а `wanted_amount`

2017-07-28 09:19 UTC, skyline-gleb commented on stf_utils/stf_connect/client.py
> +            max_sdk = specification.get("max_sdk", 99)
это ведь излишне здесь, зачем добавил?

2017-07-28 09:19 UTC, skyline-gleb commented on stf_utils/stf_connect/stf_connect.py
> +            log.warning("Poll thread is not defined, skipping... %s" % str(e))
пропустил формат)

2017-07-31 05:27 UTC, skyline-gleb requested changes

2017-07-31 05:27 UTC, skyline-gleb commented on stf_utils/stf_connect/client.py
> +        _amount = group.get("wanted_amount")
а почему просто `amount` нельзя?

2017-07-31 05:27 UTC, skyline-gleb commented on stf_utils/stf_connect/client.py
> +            resp = self._get_all_devices()
а что это за мутка с приватным/неприватным методом? из-за чего ещё и внизу тестируется теперь приватный, а не публичный метод

2017-07-31 05:27 UTC, skyline-gleb commented on tests/test_stf_connect_client.py
> +            'stf_utils.stf_connect.client.SmartphoneTestingFarmClient._get_all_devices', self.all_devices_mock,
вот про здесь говорю

2017-07-31 05:27 UTC, skyline-gleb commented on stf_utils/stf_connect/client.py
> +        time.sleep(0.1)
навсякий предлагаю сохранять авторские замечание на код ` # don't ddos api =)`, а то потом к тебе уже вопросы будут - а почему))

2017-07-31 05:27 UTC, skyline-gleb commented on stf_utils/stf_connect/client.py
> +        return res
может все-таки `available_devices` и `useful_devices` не свойства? предлагаю обсудить. мой аргумент - это не похоже на свойства :)
А ещё оба метода делают почти одно и тоже, но логи выводят совсем по разному..странно

2017-07-31 05:27 UTC, skyline-gleb commented on stf_utils/stf_connect/client.py
> +    def is_useful(self, serial):
в `is_available` и `is_useful` смущает что пропала префикс `device`. Получислось что теперь `client.is_useful(<serial>)`

2017-07-31 05:33 UTC, z00sts commented on stf_utils/stf_connect/client.py
> +        _amount = group.get("wanted_amount")
можно

2017-07-31 05:33 UTC, z00sts commented on stf_utils/stf_connect/client.py
> +    def is_useful(self, serial):
да, пожалуй

2017-07-31 05:33 UTC, z00sts commented on stf_utils/stf_connect/client.py
> +        time.sleep(0.1)
ок)

2017-07-31 05:33 UTC, z00sts commented on stf_utils/stf_connect/client.py
> +        return res
1) stf.available_devices - `ферма.доступные_девайсы`, вполне свойство
2) пожалуй, можно в info писать в useful_devices

2017-07-31 05:33 UTC, z00sts commented on stf_utils/stf_connect/client.py
> +            resp = self._get_all_devices()
Мокается, а не тестируется. Для удобства тестирования завернул вызов родительского get_all_devices в _get_all_devices

2017-07-31 05:42 UTC, sh0ked requested changes

2017-07-31 05:42 UTC, sh0ked commented on stf_utils/stf_connect/client.py
> +                                 device_group.get("group_name")))
а почему в некоторых местах заменил на .format, а где-то так и оставил?

2017-07-31 05:42 UTC, sh0ked commented on stf_utils/stf_connect/client.py
> +        return False
тут был отлов эксепшнов, теперь не нужно чтоли?

2017-07-31 05:42 UTC, sh0ked commented on stf_utils/stf_connect/client.py
> +        return res
а мне кажется норм, нормальные такие свойства же

2017-07-31 05:44 UTC, z00sts commented on stf_utils/stf_connect/client.py
> +                                 device_group.get("group_name")))
тут забыл

2017-07-31 05:45 UTC, z00sts commented on stf_utils/stf_connect/client.py
> +        return False
Теперь это в  _get_device_state

2017-07-31 05:47 UTC, sh0ked approved these changes

2017-07-31 07:16 UTC, skyline-gleb commented on stf_utils/stf_connect/client.py
> +            resp = self._get_all_devices()
и в чем оно?

2017-07-31 09:18 UTC, z00sts commented
@skyline-gleb fixed

2017-07-31 10:37 UTC, skyline-gleb commented on stf_utils/stf_connect/client.py
> +            log.info("{} is useful".format(serial))
одни и теже грабли. тут `info`, а в `is_device_available` -> `debug`

2017-07-31 10:39 UTC, skyline-gleb submitted a review, later dismissed

2017-07-31 10:39 UTC, skyline-gleb commented on stf_utils/stf_connect/client.py
> +        log.debug("Useful devices: {}".format(res))
так тут тоже самое осталось

2017-07-31 11:30 UTC, z00sts commented on stf_utils/stf_connect/client.py
> +            log.info("{} is useful".format(serial))
чето я не понял, как это произошло :(

2017-07-31 11:33 UTC, z00sts commented on stf_utils/stf_connect/client.py
> +        log.debug("Useful devices: {}".format(res))
переделал: списки useful/available выводятся в info, по отдельному девайсу инфа - в debug

2017-08-01 02:49 UTC, z00sts commented on stf_utils/stf_connect/client.py
> +            log.info("{} is useful".format(serial))
fixed

2017-08-01 02:50 UTC, merged